app/login/forms.py
# global imports
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, IntegerField, SelectField, HiddenField, TextAreaField
from wtforms.validators import DataRequired


class PinLoginForm(FlaskForm):
    """
    Form for users to login via PIN
    """
    pin = IntegerField('PIN', validators=[DataRequired()])
    submit = SubmitField('Login with PIN')
    method_PIN = HiddenField('PIN')


class CredentialsLoginForm(FlaskForm):
    """
    Form for users to open new PresenceList
    """
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    backend = SelectField('Event Type')
    submit = SubmitField('Login with Credentials')
    method_Cred = HiddenField('Credentials')

app/login/__init__.py
import secrets
from flask import Blueprint


login_bp = Blueprint('login', __name__)


def generate_secure_pin():
    return 10000000 + secrets.randbelow(90000000)


from . import views

app/login/views.py
# app/login/views.py
from datetime import datetime

from flask import flash, redirect, render_template, url_for, request, abort, make_response
from flask_login import login_required, login_user, logout_user, current_user

from . import login_bp, generate_secure_pin
from .forms import PinLoginForm, CredentialsLoginForm
from .. import db
from ..models import PresenceList
from ..connectors import create_connectors, get_connector_by_id
from ..connectors.freebies_interface import freebies_id_string
from ..connectors.gvtool_interface import gvtool_id_string
from ..security.security import register_failed_login_attempt, register_login_success


@login_bp.route('/')
def home():
    return redirect(url_for('login.login'))


@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Handle requests to the /login route
    """

    # check if user is logged in and redirect if necessary
    if current_user.is_authenticated:
        return redirect(url_for('checkin.checkin'))

    # create forms
    pinform = PinLoginForm()
    credform = CredentialsLoginForm()
    connectors = create_connectors()

    # fill form with connectors
    conn_select = []
    for c in connectors:
        conn_select.append((c.id_string, c.human_string))
    credform.backend.choices = conn_select

    if request.method == 'POST':
        if 'method_PIN' in request.values:
            if pinform.validate_on_submit():

                # PIN form was submitted, try user login
                inputpin = pinform.pin.data

                # get all presence lists with given PIN
                presencelists = PresenceList.query.filter_by(pin=inputpin).all()

                if len(presencelists) > 1:
                    # we have a database error
                    raise Exception('Multiple PresenceList with same PIN found!')

                if len(presencelists) > 0:
                    pl = presencelists[0]
                    if pl.pin == inputpin:
                        login_user(pl)
                        register_login_success()
                        return redirect(url_for('checkin.checkin'))

                register_failed_login_attempt()
                flash('Invalid PIN.', 'error')

        elif 'method_Cred' in request.values:
            if credform.validate_on_submit():

                # credential form was submitted, check connector type
                conn = get_connector_by_id(connectors, credform.backend.data)

                # try to validate against connector
                un = credform.username.data
                pw = credform.password.data
                try:
                    token = conn.login(un, pw)
                except Exception as E:
                    register_failed_login_attempt()
                    flash(str(E), 'error')
                    return redirect(url_for('login.login'))

                # credentials are valid
                register_login_success()

                # create new user! Create new pin and check if already set.
                retrycnt = 1000
                while retrycnt > 0:
                    # create secure new random pin
                    pin = generate_secure_pin()
                    if len(PresenceList.query.filter_by(pin=pin).all()) == 0:
                        break
                    retrycnt = retrycnt - 1
                if retrycnt == 0:
                    print("Could not find a free pin! Delete some PresenceList from DB!")
                    abort(500)

                # create new user account
                npl = PresenceList(conn_type=conn.id_string, pin=pin, token=token, event_id=None)
                db.session.add(npl)
                db.session.commit()
                login_user(npl)
                return redirect(url_for('login.chooseevent'))

        else:
            print('Did not find correct hidden value in POST request.')
            abort(400)

    # load login template
    return make_response(render_template('login/login.html', pinform=pinform, credform=credform, title='Login'))


def beautify_event(raw_event, additional_fields={}):
    """
    Beautify event dict to include strings for display.
    :param raw_event: dict as returned by conn.get_event()
    :param additional_fields: dict which just gets all the keys copied to the output
    :return: dict with signup_string and time_string added
    """
    if 'signup_count' in raw_event:
        spots = 'unlimited' if raw_event['spots'] == 0 else raw_event['spots']
        raw_event['signups_string'] = "{} / {}".format(raw_event['signup_count'], spots)
    if 'time_start' in raw_event:
        raw_event['time_string'] = raw_event['time_start'].strftime('%d.%m.%Y %H:%M')
    for k in additional_fields:
        raw_event[k] = additional_fields[k]
    return raw_event


@login_bp.route('/chooseevent', methods=['GET', 'POST'])
@login_required
def chooseevent():
    """
    Handle requests to the /chooseevent route
    """

    # get connector
    connectors = create_connectors()
    pl = current_user
    conn = get_connector_by_id(connectors, pl.conn_type)
    conn.token_login(pl.token)

    # catch case where event_id is already assigned
    if pl.event_id is not None:
        abort(make_response('Cannot chose new event for already opened event.', 403))

    # gather possible events in this list
    upcoming_events = []

    # get all already tracked events
    not_found_events = []  # save event ids of events which the API fails to GET
    found_events = []
    # query all presence lists for current event type
    existing_pls = PresenceList.query \
        .filter(PresenceList.conn_type == conn.id_string) \
        .filter(PresenceList.event_id >= 0) \
        .all()
    for pl in existing_pls:
        # retreive event information from data source
        conn.set_event(pl.event_id)
        try:
            evobj = conn.get_event()
        except Exception as E:
            not_found_events.append(str(pl.event_id))
            continue
        # we found a tracked event, add it to the list
        found_events.append(pl.event_id)
        # add extra info
        extra_info = {'event_ended': pl.event_ended,
                      'pin_available': pl.pin is not None}
        upcoming_events.append(beautify_event(evobj, extra_info))

    # get upcoming events
    try:
        events = conn.get_next_events()
    except Exception as E:
        flash("Could not get next events: {}".format(E), 'error')
        return logout_and_delete_pin()
    for e in events:
        if e['_id'] not in found_events:
            extra_info = {'event_ended': False,
                          'pin_available': False}
            upcoming_events.append(beautify_event(e, extra_info))

    if len(not_found_events) > 0:
        flash('Warning: The following event IDs do '
              'not seem to exist in the chosen '
              'data source: {:s}.'.format(', '.join(not_found_events))
              , 'warning')

    # sort the list by start date (newest first)
    upcoming_events = sorted(upcoming_events,
                             key=lambda k: k['time_start'] if ('time_start' in k) else datetime(1970, 1, 1),
                             reverse=True)

    # check if we are running on GVs:
    if conn.id_string == gvtool_id_string:
        show_new_gv = True
    else:
        show_new_gv = False

    # check if we are running on Freebie Tracker:
    if conn.id_string == freebies_id_string:
        show_new_fb = True
    else:
        show_new_fb = False

    # on GET, render page
    return make_response(render_template('login/chooseevent.html',
                                         title='Choose Event',
                                         upcoming_events=upcoming_events,
                                         allow_create_new_gv=show_new_gv,
                                         allow_create_new_fb=show_new_fb
                                         ))


@login_bp.route('/chooseevent/select/<string:_id>')
@login_required
def select_chooseevent(_id):
    # get connector
    connectors = create_connectors()
    pl = current_user
    conn = get_connector_by_id(connectors, pl.conn_type)
    conn.token_login(pl.token)

    # catch case where event_id is already assigned
    if pl.event_id is not None:
        abort(403)

    # check if event ID exists:
    conn.set_event(_id)
    try:
        evobj = conn.get_event()
    except Exception as E:
        flash("Invalid event ID selected: {:s}".format(E), 'error')
        return logout_and_delete_pin()

    # check if user already exists for event id
    existing_pls = PresenceList.query.filter_by(conn_type=pl.conn_type, event_id=evobj['_id']).all()
    if len(existing_pls) > 1:
        flash('More than one tracking list found for given event. Internal DB Error.', 'error')
        logout_user()
        return redirect(url_for('login.login'))
    elif len(existing_pls) == 1:
        # we have already a pin registered for this event, open event, renew token,
        # show old pin, logout user, and redirect
        existing_pl = existing_pls[0]
        existing_pl.token = pl.token
        existing_pl.event_ended = False
        pin_to_remove = pl.pin
        existing_pin = existing_pls[0].pin
        logout_user()
        # delete just created PresenceList from database as it now will not be used
        new_pl = PresenceList.query.filter_by(pin=pin_to_remove).one()
        db.session.delete(new_pl)
        db.session.commit()
        flash('PIN already exists for this event! Use PIN {} to login.'.format(existing_pin))
        return redirect(url_for('login.login'))

    # ok, new event chosen. Set event_id in current PresenceList and go further
    pl.event_id = evobj['_id']
    db.session.commit()
    return redirect(url_for('checkin.checkin'))


@login_bp.route('/logout')
@login_required
def logout():
    """
    Handle requests to the /logout route
    """
    logout_user()
    flash('You have successfully been logged out.')

app/templates/login/chooseevent.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Choose your Event{% endblock %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center">
    <h1>Choose your Event:</h1>
    <br/>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th width="35%"> Title </th>
            <th width="20%"> Signups </th>
            <th width="25%"> Start Date </th>
            <th width="20%"> Open Tracking </th>
        </tr>
        </thead>
        <tbody>
          {% for ev in upcoming_events %}
            <tr>
              <td> {{ ev['title'] }}
                  {% if ev['event_ended'] %}
                    (closed)
                  {% endif %}
              </td>
              <td> {{ ev['signups_string'] }} </td>
              <td> {{ ev['time_string'] }}  </td>
              <td>
                <a class="table_link" href="{{ url_for('login.select_chooseevent', _id=ev['_id']) }}">
                    {% if ev['event_ended'] %}
                        reopen
                    {% elif ev['pin_available'] %}
                        get pin
                    {% else %}
                        open
                    {% endif %}
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
    <br/>
    {% if allow_create_new_gv %}
    <a href="{{ url_for('gvtool.new_gv') }}" class="btn btn-default" role="button">Open new GV</a>
    <br/><br/>
    {% endif %}
    {% if allow_create_new_fb %}
    <a href="{{ url_for('freebies.new_freebie') }}" class="btn btn-default" role="button">Open new Freebie Tracker</a>
    <br/><br/>
    {% endif %}
    <a href="{{ url_for('login.logout_and_delete_pin') }}" class="btn btn-default" role="button">Back</a>
  </div>
</div>
{% endblock %}

app/templates/login/login.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center-narrow">
    <h1>AMIV Check-In Tool</h1>
    <br/>
    {{ wtf.quick_form(pinform) }}
    <hr class="intro-divider">
    {{ wtf.quick_form(credform) }}
  </div>
</div>
{% endblock %}

app/templates/login/privacy.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Privacy Statement{% endblock %}
{% block body %}
<div class="content-section">
    <br/>
    {{ utils.flashed_messages() }}
    <br/>
    <div class="center-narrow">
        <h1>AMIV Privacy Statement</h1>
        <br/>
        <h3>AMIV Checkin Apps - Privacy Statement</h3>
        <p>Data is only ever collected from active user input, never passively or in the background. No pictures are
            saved from the camera. The camera is only used to detect barcodes and is only active when the camera preview
            is displayed on-screen within the app. The barcodes or user text input will be sent to a secure AMIV server
            where they are used for tracking event attendance of persons registered at ETH and/or the AMIV member
            directory only.If the sent data does not correspond to any person registered at the ETH then the data is
            discarded. No data is collected which is unrelated to the functionality of the app. The data is not shared
            with any third parties. The data is purely used by entitled members of the AMIV. If you would prefer not to
            have this data shared with the AMIV servers, please uninstall the app or do not open/use the app. There is
            no way to prevent the data being sent to AMIV servers as this is the core functionality of the app. Whereby
            AMIV represents the 'Akademischer Maschinen- und Elektroingenieur Verein' at ETH Zurich, Switzerland.</p>
        <br/>
        <a href="{{ url_for('login.login') }}" class="btn btn-default" role="button">Back</a>
    </div>
</div>
{% endblock %}