app/checkin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, RadioField
from wtforms.validators import DataRequired


class CheckForm(FlaskForm):
    """
    Check-in or check-out users.
    """
    checkmode = RadioField('checkmode',
                           validators=[DataRequired()],
                           choices=[('in', 'Check-In'), ('out', 'Check-Out')])
    datainput = StringField('Legi #, nethz, or email',
                            validators=[DataRequired()],
                            render_kw={'autofocus': True, 'onFocus': 'this.select();'})
    submit = SubmitField('Submit')


class CSRFCheckForm(FlaskForm):
    """
    This form does not contain anything except the automatically inserted CSRF token hidden field
    """
    pass

app/checkin/__init__.py
from flask import Blueprint

checkin_bp = Blueprint('checkin', __name__)

from . import views

app/checkin/views.py
# app/checkin/views.py

from flask import flash, redirect, render_template, url_for, request, make_response, abort, jsonify, Response
from flask_login import login_required, logout_user, current_user
import csv
import datetime
from io import StringIO

from . import checkin_bp
from .forms import CheckForm, CSRFCheckForm
from .. import db
from ..login import generate_secure_pin
from ..models import PresenceList
from ..connectors import create_connectors, get_connector_by_id
from ..security.security import register_failed_login_attempt, register_login_success


@checkin_bp.route('/checkin', methods=['GET', 'POST'])
@login_required
def checkin():
    """
    Main Webpage for all the signups. Also takes requests
    from the manual check-in / check-out form.
    """

    # get connector
    connectors = create_connectors()
    pl = current_user
    conn = get_connector_by_id(connectors, pl.conn_type)
    conn.token_login(pl.token)

    # if this pl has not set an event id yet, redirect to chooseevent
    if pl.event_id is None:
        return redirect(url_for('login.chooseevent'))

    # event is set, setup connector
    conn.set_event(pl.event_id)

    # create form
    checkform = CheckForm()

    # check form submission
    if checkform.validate_on_submit():
        checkmode = checkform.checkmode.data
        info = checkform.datainput.data

        try:
            if pl.event_ended:
                raise Exception('Event ended. No changes allowed.')
            if checkmode == 'in':
                rd = conn.checkin_field(info)
                flash(rd['message'])
            else:
                rd = conn.checkout_field(info)
                flash(rd['message'])
        except Exception as E:
            flash('Error: ' + str(E), 'error')

    # fetch title and description
    try:
        evobj = conn.get_event()
        event_title = evobj['title']
        if 'time_start' in evobj:
            event_start = evobj['time_start'].strftime('%d.%m.%Y %H:%M')
        else:
            event_start = ""
    except Exception as E:
        flash('Error: ' + str(E), 'error')
        event_title = "< unknown >"
        event_start = ""

    # enable button for log download if the current connector offers a get_log() function
    # to allow the user to download the .csv log
    if "get_log" in dir(conn):
        show_log_btn = True
    else:
        show_log_btn = False

    # load webpage
    return make_response(render_template('checkin/checkin.html',
                                         form=checkform,
                                         event_ended=pl.event_ended,
                                         event_title=event_title,
                                         event_start=event_start,
                                         log_download=show_log_btn,
                                         csrfcheckform=CSRFCheckForm(),
                                         title='AMIV Check-In'))


@checkin_bp.route('/checkin_update_data')
def checkin_update_data():
    """
    Delivers the table contents on the webpage.
    """

    # check if pin is supplied
    pin = request.headers.get('pin')
    if pin is None:
        # if no pin is supplied, check if we are logged in
        if not current_user.is_authenticated:
            abort(make_response('Not logged in.', 401))
        pl = current_user
    else:
        # pin supplied, find current user via database
        pls = PresenceList.query.filter_by(pin=pin).all()
        if len(pls) != 1:
            register_failed_login_attempt()
            abort(make_response('PIN invalid.', 401))
        else:
            register_login_success()
            pl = pls[0]

    if pl.event_id is None:
        abort(make_response('No registered event for this PIN.', 400))

    # find appropriate connector
    conn = get_connector_by_id(create_connectors(), pl.conn_type)
    conn.token_login(pl.token)

    # event is set, setup connector
    conn.set_event(pl.event_id)

    # get current signups
    try:
        signups = conn.get_signups_for_event()
    except Exception as E:
        abort(make_response('Error with API access: {:s}'.format(repr(E)), 502))

    # sort signups
    signups.sort(key=lambda su: int(su['position']))

    # fetch statistics
    try:
        stats = conn.get_statistics()
    except Exception as E:
        abort(make_response('Error with API access: {:s}'.format(repr(E)), 502))
    statsl = list()
    for k in stats:
        statsl.append({'key': k, 'value': stats[k]})

    # fetch information about event
    try:
        evobj = conn.get_event()
    except Exception as E:
        abort(make_response('Error with API access: {:s}'.format(repr(E)), 502))
    evobj['event_type'] = conn.human_string  # add description of event type

    j = {'signups': signups, 'statistics': statsl, 'eventinfos': evobj}
    return make_response(jsonify(j))


@checkin_bp.route('/change_pin', methods=['POST'])
@login_required
def change_pin():
    """
    Generates a new pin for the user and logs the user out.
    """

    # do CSRF check on POST data
    cpform = CSRFCheckForm()
    if not cpform.validate():
        abort(make_response('CSRF check failed.', 400))

    # create new pin and check if already occupied
    retrycnt = 1000
    while retrycnt > 0:
        # create secure new random pin
        newpin = generate_secure_pin()
        if PresenceList.query.filter_by(pin=newpin).count() == 0:
            break
        retrycnt = retrycnt - 1
    if retrycnt == 0:
        print("Could not find a free pin! Delete some PresenceList from DB!")
        abort(500)

    # logout user and change pin
    pin_to_change = current_user.pin
    logout_user()
    pl = PresenceList.query.filter_by(pin=pin_to_change).one()
    pl.pin = newpin
    db.session.commit()

    # inform user and redirect
    flash('PIN changed! Use new PIN {} to login.'.format(newpin))
    return redirect(url_for('login.login'))


@checkin_bp.route('/close_event', methods=['POST'])
@login_required
def close_event():
    """
    Closes the event.
    """

    # do CSRF check on POST data
    cpform = CSRFCheckForm()
    if not cpform.validate():
        abort(make_response('CSRF check failed.', 400))

    # check if already closed
    pl = current_user
    if pl.event_ended:
        abort(make_response('Event already closed.', 400))

    # setup connector
    conn = get_connector_by_id(create_connectors(), pl.conn_type)
    conn.token_login(pl.token)
    conn.set_event(pl.event_id)

    try:
        # checkout all checked-in users
        conn.checkout_all_remaining()
    except Exception as E:
        flash('Error: ' + str(E), 'error')
        return redirect(url_for('checkin.checkin'))

    # mark event as ended
    pl.event_ended = True
    db.session.commit()

    # inform user and redirect
    flash('Event closed.')
    return redirect(url_for('checkin.checkin'))


@checkin_bp.route('/export_csv')
@login_required
def export_csv():
    """
    Let the user download a CSV file with all user check-in and check-out timestamps
    """

    # get connector
    connectors = create_connectors()
    pl = current_user
    conn = get_connector_by_id(connectors, pl.conn_type)
    conn.token_login(pl.token)

    # catch if user did not choose an appropriate backend for log exprting
    if "get_log" not in dir(conn):
        abort(make_response('Cannot export CSV for a backend not providing get_log() function.', 403))

    # catch case if the event is not chosen yet
    if pl.event_id is None:
        abort(make_response('Cannot export CSV for PresenceList with no assigned event ID.', 403))

    # retrieve list of cleaned log entries
    conn.set_event(pl.event_id)
    try:
        event_reference = conn.get_event()
        loglist = conn.get_log()
    except Exception as E:
        abort(make_response('Error with API access: {:s}'.format(str(E)), 502))

    # assemble csv output file
    outcsv = StringIO()  # creates a memory-mapped file structure
    nlchar = '\r\n'

    # header
    outcsv.write('// AMIV Checkin Log File' + nlchar)
    outcsv.write('// {:s}'.format(event_reference['title']) + nlchar)
    if 'time_start' in event_reference:
        outcsv.write('// {:s}'.format(event_reference['time_start'].strftime('%d.%m.%Y %H:%M')) + nlchar)
    if 'description' in event_reference:
        desc = event_reference['description'].replace('\n', '\n// ')
        outcsv.write('// {:s}'.format(desc) + nlchar)
    if len(loglist) > 0:
        outcsv.write('// Columns: ' + ', '.join(['"' + str(k) + '"' for k, _ in loglist[0].items()]) + nlchar)

    # add log data
    csvwriter = csv.writer(outcsv, delimiter=',', quotechar='"', quoting=csv.QUOTE_ALL)
    for log in loglist:
        csvwriter.writerow([v for _, v in log.items()])

    # create filename
    fn = 'AMIV_Checkin_Log_{:s}'.format(str(int(datetime.datetime.now().timestamp())))

    # return response (this results in a download file dialog in most browsers)
    return Response(
        outcsv.getvalue(),
        mimetype="text/csv",
        headers={"Content-disposition": "attachment; filename={:s}.csv".format(fn)})

app/templates/checkin/checkin.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block javascript %}
<script type="text/javascript">
    {% include "checkin/update_tables.js" %}
    {% include "checkin/confirm_new_pin.js" %}
    {% include "checkin/confirm_close_event.js" %}
</script>
{% endblock %}

{% block body %}
<div class="center">

    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="{{ url_for('login.login') }}">AMIV Check-In</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('login.logout') }}">Logout</a></li>
                    <li><a id="change_pin_link" href="#" onclick="confirm_new_pin();return false;">Change PIN</a></li>
                    <li><a><i class="fa fa-user"></i> Your current PIN: {{ current_user.pin }}</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="content-section"><br/>

        <h1>{{ event_title }}</h1>
        <h3>{{ event_start }}</h3>
        {% if event_ended %}
        <h4>(Event closed. No changes allowed.)</h4>
        {% endif %}

        {{ utils.flashed_messages(container=False) }}<br/>

        <div id="sync_warning" style="display:none">
            <div class="alert alert-warning" id="sync_warning_alert">
                <strong>Warning!</strong> Could not fetch new data from server. List might be outdated. <div id="sync_warning_reason"></div>
            </div>
            <br/>
        </div>

        {% if not event_ended %}
        {{ wtf.quick_form(form, form_type='horizontal', horizontal_columns=('md', 2, 10)) }}
        <hr class="intro-divider">
        {% endif %}

        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th colspan="2"> Statistics</th>
            </tr>
            </thead>
            <tbody id="tbody_statistics">
            <tr>
                <td width="85%"> Loading... </td>
                <td width="15%"> </td>
            </tr>
            </tbody>
        </table>

        <hr class="intro-divider">

        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th width="25%"> Name </th>
                <th width="10%"> nethz </th>
                <th width="10%"> Legi </th>
                <th width="30%"> e-Mail </th>
                <th width="15%"> Membership </th>
                <th width="10%"> Status </th>
            </tr>
            </thead>
            <tbody id="tbody_signups">
            <tr>
                <td> Loading... </td>
                <td> </td>
                <td> </td>
                <td> </td>
                <td> </td>
                <td> </td>
            </tr>
            </tbody>
        </table>

        <h4>
            Regular Members
        </h4>
        <p id="regular_names" style="margin-bottom: 25px">
            Loading...
        </p>
        <b></b>
        <h4>
            Extraordinary Members
        </h4>
        <p id="extraordinary_names" style="margin-bottom: 25px">
            Loading...
        </p>
        
        <h4>
            Honorary Members
        </h4>
        <p id="honorary_names" style="margin-bottom: 25px">
            Loading...
        </p>

        <h4>
            No Members
        </h4>
        <p id="none_names" style="margin-bottom: 25px">
            Loading...
        </p>

        
        {% if log_download %}
        <br/>
        <a href="{{ url_for('checkin.export_csv') }}" class="center-block">
            <button class="btn btn-default center-block"> Export Log as .csv File </button>
        </a>
        {% endif %}

        {% if not event_ended %}
        <br/>
        <a id="close_event_link" href="#" onclick="confirm_close_event();return false;" class="center-block">
            <button class="btn btn-default center-block"> Close Event </button>
        </a>
        {% endif %}
    </div>
</div>
{% endblock %}